### ISSUE TITLE
4월 둘째 주 TODO

### ISSUE THREAD

**Issue by seohyun-lee** [TeamMuzik/MuzikIsMyLife#160]
- [x] 상점 포스터 이미지 빠져서 넣음
- [x] 스마트폰 앱에 휴식 기능 넣음 (behaviorId: 7)
- [x] 게임 종료를 status 창의 X btn 클릭으로 변경함 (behaviorId: 7 -> -1(기본값)로 변경)
- [x] Main씬의 status 날짜 - 게임 종료를 눌러서 종료하지 않고 강제 종료해도 날짜 바뀌지 않도록
- [x] #166
- [x] #165
- [x] 캐릭터 자는 이미지 교체
